name: Android APK Release Build

# This workflow is triggered on push events to branches that start with 'release/'.

on:
  push:
    branches:
      - 'release/**'
      - 'ci/**'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      # Load google-services.json and local.properties from the secrets
      - name: Decode secrets
        env:
          KEYSTORE: ${{ secrets.KEYSTORE_BASE_64 }}
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          echo "$KEYSTORE" | base64 --decode > ./app/upload-keystore.jks
          echo "$GOOGLE_SERVICES" | base64 --decode > ./app/google-services.json
          echo "$LOCAL_PROPERTIES" | base64 --decode > ./local.properties
          echo "$KEYSTORE_PROPERTIES" | base64 --decode > ./keystore.properties

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Build the APK
      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk