name: Android APK Build

on:
  push:
    branches:
      - 'release/**' # Only trigger on branches starting with 'release/'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    # Load google-services.json and local.properties from the secrets
    - name: Decode secrets
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      run: |
        echo "$GOOGLE_SERVICES" | base64 --decode > ./app/google-services.json
        echo "$LOCAL_PROPERTIES" | base64 --decode > ./local.properties

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

      # Run Build Project
    - name: Build gradle project
      run: ./gradlew build
        
    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk
